Draft release notes for Klaw documentation
aiven/klaw-docs pull request #42
Opened 2023-02-24 10:50 UTC by aindriu-aiven

Draft release notes for Klaw documentation.

Includes features and points to new documentation where possible for those new features.

2023-02-24 11:12 UTC, muralibasani commented on docs/releases/release210.rst
> +- **Approve & Reject Schema Request**: Users can now approve or reject schema requests using the new UI.
```suggestion
- **Approve & Reject Schema Requests**: Users can now approve or reject schema requests using the new UI.
```

2023-02-24 11:13 UTC, muralibasani commented on docs/releases/release210.rst
> +`````````````````
```suggestion
``````````````
```

2023-02-24 11:13 UTC, muralibasani commented on docs/releases/release210.rst
> +`````````````````````````````````````````````````````
```suggestion
```````````````
```

2023-02-24 11:14 UTC, muralibasani commented on docs/releases/release210.rst
> +Klaw now supports Confluent Cloud Topics, Acls.
```suggestion
Klaw now supports Confluent Cloud Kafka Topics, Acls.
```

2023-02-24 11:15 UTC, muralibasani commented on docs/releases/release210.rst
> +Confluent Cloud
```suggestion
Confluent Cloud Kafka
```

2023-02-24 11:15 UTC, muralibasani requested changes
few minor ones, rest looks good

2023-02-24 12:55 UTC, muralibasani commented on docs/releases/release210.rst
> +Switching Teams
```suggestion
Switching Teams
~~~~~~~~~~~~
```

2023-02-24 13:46 UTC, harshini-rangaswamy requested changes
Minor suggestions.

2023-02-24 13:46 UTC, harshini-rangaswamy commented on docs/releases/release210.rst
> +To preview the new Klaw user user interface, open the ``application.properties`` file on the Klaw **core** module, and set the value of the following property to ``true``:
```suggestion
To preview the new Klaw user interface, open the ``application.properties`` file on the Klaw **core** module, and set the value of the following property to ``true``:
```

2023-02-24 13:46 UTC, harshini-rangaswamy commented on docs/releases/release210.rst
> +https://docs.confluent.io/cloud/current/api.html#tag/ACL-(v3)
```suggestion
Klaw now offers Confluent Cloud Kafka Topics and ACLs support, expanding its capabilities to interact with Confluent Cloud Kafka. This release includes the implementation of the following APIs:
https://docs.confluent.io/cloud/current/api.html#tag/Topic-(v3)
https://docs.confluent.io/cloud/current/api.html#tag/ACL-(v3)
```

2023-02-24 13:46 UTC, harshini-rangaswamy commented on docs/releases/release210.rst
> +Switching Teams
Suggest calling it "Switch Teams"

2023-02-24 13:46 UTC, harshini-rangaswamy commented on docs/releases/release210.rst
> +With this release, users now have the ability to be a member of multiple teams and switch between those teams without logging out and logging back in. Allowing a single user to have proper auditable
```suggestion
Klaw now allows users to be members of multiple teams and easily switch between them without needing to log out and back in. With this new functionality, a single user can now have proper auditable capabilities while working across multiple teams. Additionally, users will benefit from increased flexibility and efficiency when working within the Klaw platform, particularly when creating or approving requests.
```

2023-02-28 10:29 UTC, aindriu-aiven commented on docs/releases/release210.rst
> +
This image is missing and is needed.

2023-03-01 16:10 UTC, harshini-rangaswamy approved these changes
LGTM!

2023-03-06 08:12 UTC, muralibasani approved these changes
LGTM

2023-03-06 09:20 UTC, merged