Release notes for release 2.2.0
aiven/klaw-docs pull request #48
Opened 2023-04-03 08:15 UTC by aindriu-aiven

Release notes highlighting new 2.2.0 release and some of the features available in this release.

2023-04-03 08:37 UTC, muralibasani commented on docs/releases/release220.rst
> +Klaw now masks IP Address's and Service Account names from all users except the ACL owner, ensuring better security for users.
```suggestion
Klaw now masks IP Addresses, certificates and Service Account credentials from all users except the ACL owner, ensuring better security for users.
```

2023-04-03 08:40 UTC, muralibasani commented on docs/releases/release220.rst
> +Klaw will now check all Schema compatibility against the Schema Registry before creating the Schema Creation requests. This feature will only be bypassed used when forceRegister is in use.
It's abit unclear here 'bypassed used when forceRegister'

2023-04-03 14:41 UTC, muralibasani commented on docs/releases/release220.rst
> +Date: 3rd of April, 2023
```suggestion
Date: 5th of April, 2023
```

2023-04-05 07:28 UTC, muralibasani approved these changes
LGTM, thanks

2023-04-05 09:00 UTC, harshini-rangaswamy requested changes
Looks good. A few minor suggestions.

2023-04-05 09:19 UTC, programmiri commented on docs/releases/release220.rst
> +.. image:: /../../../_static/images/ApprovalRequestTopic-react.png
wrong  🖼️  link!

2023-04-05 09:37 UTC, programmiri approved these changes

2023-04-05 09:58 UTC, harshini-rangaswamy requested changes
Changes to sentence casing.

2023-04-05 09:58 UTC, harshini-rangaswamy commented on docs/releases/release220.rst
> +Pre Validation of Schema Compatibility
```suggestion
Pre-validation of schema compatibility
```

2023-04-05 09:58 UTC, harshini-rangaswamy commented on docs/releases/release220.rst
> +Klaw will now check all Schema compatibility against the Schema Registry before creating the Schema Creation requests. This feature will only be bypassed during promotion when the 'force register sch
```suggestion
Klaw will now check all schema compatibility against the Schema Registry before creating the schema creation requests. This feature will only be bypassed during promotion when the 'force register schema' option is selected.
```

2023-04-05 09:58 UTC, harshini-rangaswamy commented on docs/releases/release220.rst
> +ACL information is now masked
```suggestion
Masking of ACL information for enhanced security
```

2023-04-05 09:58 UTC, harshini-rangaswamy commented on docs/releases/release220.rst
> +Export Data to JSON
```suggestion
Export data to JSON
```

2023-04-05 10:05 UTC, harshini-rangaswamy approved these changes

2023-04-05 10:09 UTC, merged