Update docs regarding coral enabled default
aiven/klaw-docs pull request #60
Opened 2023-06-19 14:35 UTC by programmiri

# Changes

Since release 2.4.0 the coral preview is enabled by default. This PR updates:

- the docs how to setup Klaw from source -> informs user that React UI is enabled by default and how to disabled it if they want to
- the release notes for 2.4.0 -> same as above it informs user how to disable the preview if they want to

2023-06-19 15:30 UTC, harshini-rangaswamy requested changes
@programmiri, just a minor change.

2023-06-19 15:30 UTC, harshini-rangaswamy commented on docs/docs/howto/installation/run-source.rst
> +   you can disabled it:
```suggestion
   you can disable it:
```

2023-06-19 15:30 UTC, harshini-rangaswamy commented on docs/releases/release240.rst
> +To disabled the preview for the new Klaw user interface, open the ``application.properties`` file on the Klaw
```suggestion
To disable the preview for the new Klaw user interface, open the ``application.properties`` file on the Klaw
```

2023-06-20 06:38 UTC, programmiri commented
Thank you @harshini-rangaswamy! Not sure what was wrong with me and the word "disable" yesterday 😅  Can you check again and approve if everything is ok? 🙏

2023-06-20 07:04 UTC, harshini-rangaswamy approved these changes
LGTM!

2023-06-20 07:26 UTC, merged